apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-metrics-app
  labels:
    app: websocket-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-metrics-app
  template:
    metadata:
      labels:
        app: websocket-metrics-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: websocket-metrics-app
        image: quay.io/sureshgaikwad/websocket-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
